---


all:
  children:

    # aerospike-amc:
    #   hosts:
    #     aerospike-amc-host-1:
    #       ansible_ssh_host: 'aerospike-1.databases.zm.private'
    #     aerospike-amc-host-2:
    #       ansible_ssh_host: 'aerospike-2.databases.zm.private'
    #     aerospike-amc-host-3:
    #       ansible_ssh_host: 'aerospike-3.databases.zm.private'
    #     aerospike-amc-host-4:
    #       ansible_ssh_host: 'aerospike-4.databases.zm.private'
    #     aerospike-amc-host-5:
    #       ansible_ssh_host: 'aerospike-5.databases.zm.private'
    #     aerospike-amc-host-6:
    #       ansible_ssh_host: 'aerospike-6.databases.zm.private'
    #     aerospike-amc-host-7:
    #       ansible_ssh_host: 'aerospike-7.databases.zm.private'
    #     aerospike-amc-host-8:
    #       ansible_ssh_host: 'aerospike-8.databases.zm.private'
    #     aerospike-amc-host-9:
    #       ansible_ssh_host: 'aerospike-9.databases.zm.private'
    #     aerospike-amc-host-10:
    #       ansible_ssh_host: 'aerospike-10.databases.zm.private'
    #     aerospike-amc-host-11:
    #       ansible_ssh_host: 'aerospike-11.databases.zm.private'
    #     aerospike-amc-host-12:
    #       ansible_ssh_host: 'aerospike-12.databases.zm.private'
    #     aerospike-amc-host-13:
    #       ansible_ssh_host: 'aerospike-13.databases.zm.private'
    #     aerospike-amc-host-14:
    #       ansible_ssh_host: 'aerospike-14.databases.zm.private'
    #     aerospike-amc-host-15:
    #       ansible_ssh_host: 'aerospike-15.databases.zm.private'
    #     aerospike-amc-host-16:
    #       ansible_ssh_host: 'aerospike-15.databases.zm.private'
    #     aerospike-amc-host-17:
    #       ansible_ssh_host: 'aerospike-15.databases.zm.private'
    #     aerospike-amc-host-18:
    #       ansible_ssh_host: 'aerospike-15.databases.zm.private'

    aerospikeeast:
      hosts:
        aerospike-1.databases.groveops.net:

          
    # aerospikewest:
    #   hosts:
    #     # aerospike-in-memory-1.databases-west.zm.private:
    #     # aerospike-in-memory-2.databases-west.zm.private:
    #     # aerospike-in-memory-3.databases-west.zm.private:
    #     # aerospike-in-memory-4.databases-west.zm.private:
    #     # aerospike-in-memory-5.databases-west.zm.private:

  vars:
    ansible_connection: ssh
    ansible_ssh_user: "{{ lookup('env', 'USER') }}"
    environment: databases
    aws_cwa_metrics_namespace: "vpc-databases"